// This file was auto generated by Styx.
// Do not edit this file directly.

import type { Runner, Execution, Metadata, InputPathType } from "styxdefs";
import { getGlobalRunner } from "styxdefs";

export const GREET_METADATA: Metadata = {
  id: "greet",
  name: "greet",
  package: "unknown",
};

export interface Greet {
  "@type"?: "unknown/greet";
  /** Person to greet. */
  name: string;
  /** Shout the greeting. */
  loud?: boolean;
}

/** Build command-line arguments from parameters. */
export function greet_cargs(params: Greet, execution: Execution): string[] {
  const cargs: string[] = [];
  cargs.push("greet");
  cargs.push(params.name);
  if (params.loud) {
    cargs.push("--loud");
  }
  return cargs;
}

/**
 * greet
 * 
 * Print a greeting.
 *
 * @param params - The parameters.
 * @param runner - Command runner (defaults to global runner).
 */
export function greet(params: Greet, runner: Runner | null = null): void {
  runner = runner ?? getGlobalRunner();
  const execution = runner.startExecution(GREET_METADATA);
  execution.params(params);
  const args = greet_cargs(params, execution);
  execution.run(args);
}
