# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, get_global_runner

GREET_METADATA = Metadata(
    id="greet",
    name="greet",
    package="unknown",
)

class Greet(typing.TypedDict):
    name: str
    """Person to greet."""
    loud: bool | None
    """Shout the greeting."""

def greet_cargs(params: Greet, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("greet")
    cargs.append(params["name"])
    if params["loud"]:
        cargs.append("--loud")
    return cargs

def greet(params: Greet, runner: Runner | None = None) -> None:
    """
    greet
    
    Print a greeting.
    
    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).
    
    Returns:
        None.
    """
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(GREET_METADATA)
    execution.params(params)
    args = greet_cargs(params, execution)
    execution.run(args)

__all__ = [
    "Greet",
    "GREET_METADATA",
    "greet_cargs",
    "greet",
]