# This file was auto generated by Styx.
# Do not edit this file directly.

import pathlib
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, StyxValidationError, OutputPathType, get_global_runner

GREET_METADATA = Metadata(
    id="greet",
    name="greet",
    package="unknown",
)

class Greet(typing.TypedDict):
    name: str
    """Person to greet."""
    loud: typing.NotRequired[bool]
    """Shout the greeting."""

class GreetOutputs(typing.NamedTuple):
    """Output paths produced by the tool."""
    root: OutputPathType

def greet_params(
    name: str,
    loud: bool = False,
) -> Greet:
    """
    Build parameters.

    Args:
        name: Person to greet.
        loud: Shout the greeting.

    Returns:
        Parameter dictionary.
    """
    params: Greet = {
        "name": name,
        "loud": loud,
    }
    return params

def greet_validate(params: typing.Any) -> None:
    """Validate untrusted parameters. Raises StyxValidationError if `params` is not a valid Greet."""
    if params is None or not isinstance(params, dict):
        raise StyxValidationError(f'Params object has the wrong type \'{type(params)}\'')
    if params.get("name", None) is None:
        raise StyxValidationError("`name` must not be None")
    if not isinstance(params["name"], str):
        raise StyxValidationError(f'`name` has the wrong type: Received `{type(params["name"])}` expected `str`')
    if params.get("loud", None) is not None:
        if not isinstance(params["loud"], bool):
            raise StyxValidationError(f'`loud` has the wrong type: Received `{type(params["loud"])}` expected `bool`')

def greet_cargs(params: Greet, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("greet")
    cargs.append(params["name"])
    if params.get("loud"):
        cargs.append("--loud")
    return cargs

def greet_outputs(params: Greet, execution: Execution) -> GreetOutputs:
    """Build the GreetOutputs object for this tool."""
    root_v: OutputPathType = execution.output_file(".")
    return GreetOutputs(
        root=root_v,
    )

def greet_execute(params: Greet, runner: Runner | None = None) -> GreetOutputs:
    """
    greet

    Print a greeting.

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    greet_validate(params)
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(GREET_METADATA)
    execution.params(params)
    args = greet_cargs(params, execution)
    out = greet_outputs(params, execution)
    execution.run(args)
    return out

def greet(
    name: str,
    loud: bool = False,
    runner: Runner | None = None,
) -> GreetOutputs:
    """
    greet

    Print a greeting.

    Args:
        name: Person to greet.
        loud: Shout the greeting.
        runner: Command runner (defaults to global runner).

    Returns:
        Tool outputs (paths to files produced by the tool).
    """
    params = greet_params(
        name=name,
        loud=loud,
    )
    return greet_execute(params, runner)

__all__ = [
    "Greet",
    "GreetOutputs",
    "GREET_METADATA",
    "greet_cargs",
    "greet_outputs",
    "greet_params",
    "greet_execute",
    "greet_validate",
    "greet",
]