// This file was auto generated by Styx.
// Do not edit this file directly.

import type { Runner, Execution, Metadata, InputPathType } from "styxdefs";
import { getGlobalRunner, StyxValidationError } from "styxdefs";

export const GREET_METADATA: Metadata = {
  id: "greet",
  name: "greet",
  package: "unknown",
};

export interface Greet {
  "@type"?: "unknown/greet";
  /** Person to greet. */
  name: string;
  /** Shout the greeting. */
  loud: boolean;
}

/**
 * Build parameters.
 *
 * @param name Person to greet.
 * @param loud Shout the greeting.
 *
 * @returns Parameter object.
 */
export function greetParams(
  name: string,
  loud: boolean = false,
): Greet {
  const params: Greet = {
    "@type": "unknown/greet",
    name: name,
    loud: loud,
  };
  return params;
}

/** Validate the parameters. Throws StyxValidationError if the parameters are invalid. */
export function greetValidate(params: Greet): void {
  if (typeof params !== "object" || params === null) {
    throw new StyxValidationError("Params object has the wrong type");
  }
  if (params.name == null) {
    throw new StyxValidationError("`name` must not be null");
  }
  if (typeof params.name !== "string") {
    throw new StyxValidationError("`name` has the wrong type (expected string)");
  }
  if (params.loud != null) {
    if (typeof params.loud !== "boolean") {
      throw new StyxValidationError("`loud` has the wrong type (expected boolean)");
    }
  }
}

/** Build command-line arguments from parameters. */
export function greet_cargs(params: Greet, execution: Execution): string[] {
  const cargs: string[] = [];
  cargs.push("greet");
  cargs.push(params.name);
  if (params.loud) {
    cargs.push("--loud");
  }
  return cargs;
}

/**
 * greet
 * 
 * Print a greeting.
 *
 * @param params - The parameters.
 * @param runner - Command runner (defaults to global runner).
 */
export function greetExecute(params: Greet, runner: Runner | null = null): void {
  greetValidate(params);
  runner = runner ?? getGlobalRunner();
  const execution = runner.startExecution(GREET_METADATA);
  execution.params(params);
  const args = greet_cargs(params, execution);
  execution.run(args);
}

/**
 * greet
 *
 * Print a greeting.
 *
 * @param name Person to greet.
 * @param loud Shout the greeting.
 * @param runner Command runner (defaults to global runner).
 *
 * @returns void
 */
export function greet(
  name: string,
  loud: boolean = false,
  runner: Runner | null = null,
): void {
  const params = greetParams(
    name,
    loud,
  );
  greetExecute(params, runner);
}
