# This file was auto generated by Styx.
# Do not edit this file directly.

import dataclasses
import typing

from styxdefs import Execution, InputPathType, Metadata, Runner, get_global_runner

GREET_METADATA = Metadata(
    id="greet",
    name="greet",
    package="unknown",
)

class Greet(typing.TypedDict):
    name: str
    """Person to greet."""
    loud: bool | None
    """Shout the greeting."""

def greet_params(
    name: str,
    loud: bool = False,
) -> Greet:
    """
    Build params.

    Args:
        name: Person to greet.
        loud: Shout the greeting.

    Returns:
        Params dictionary.
    """
    params: Greet = {
        "name": name,
        "loud": loud,
    }
    return params

def greet_cargs(params: Greet, execution: Execution) -> list[str]:
    """Build command-line arguments from parameters."""
    cargs: list[str] = []
    cargs.append("greet")
    cargs.append(params["name"])
    if params["loud"]:
        cargs.append("--loud")
    return cargs

def greet_execute(params: Greet, runner: Runner | None = None) -> None:
    """
    greet

    Print a greeting.

    Args:
        params: The parameters.
        runner: Command runner (defaults to global runner).

    Returns:
        None.
    """
    runner = runner if runner is not None else get_global_runner()
    execution = runner.start_execution(GREET_METADATA)
    execution.params(params)
    args = greet_cargs(params, execution)
    execution.run(args)

def greet(
    name: str,
    loud: bool = False,
    runner: Runner | None = None,
) -> None:
    """
    greet

    Print a greeting.

    Args:
        name: Person to greet.
        loud: Shout the greeting.
        runner: Command runner (defaults to global runner).

    Returns:
        None.
    """
    params = greet_params(
        name=name,
        loud=loud,
    )
    greet_execute(params, runner)

__all__ = [
    "Greet",
    "GREET_METADATA",
    "greet_cargs",
    "greet_params",
    "greet_execute",
    "greet",
]