import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { describe, expect, it } from "vitest";
import { ArgtypeParser } from "../../frontend/argtype/parser-frontend.js";
import { generateArgtype } from "./emit.js";

/**
 * Structural round-trip: parse -> IR -> emit -> parse -> IR, asserting the two
 * IRs are structurally equal. The emitter reproduces exactly the IR the
 * frontend lowers to, so no normalization is needed:
 * - `set`/`any` never appear (the frontend already lowered them away), so there
 *   is nothing for the emitter to recover.
 * - Output declarations live on the root sequence (the frontend collects them
 *   there), so the emitter re-emits them on the root and they re-collect 1:1.
 * - The `opt(literal)` flag-false default is regenerated by the frontend, so the
 *   emitter omits it and it reappears on the re-parse.
 */

const parser = new ArgtypeParser();

function fixture(name: string): string {
  return readFileSync(fileURLToPath(new URL(`./__fixtures__/${name}`, import.meta.url)), "utf8");
}

function frontendFixture(name: string): string {
  return readFileSync(
    fileURLToPath(new URL(`../../frontend/argtype/__fixtures__/${name}`, import.meta.url)),
    "utf8",
  );
}

function roundTrip(source: string) {
  const first = parser.parse(source);
  expect(first.errors).toEqual([]);

  const { source: emitted, warnings } = generateArgtype(first.expr, first.meta);

  const second = parser.parse(emitted);
  expect(second.errors, `re-parse failed:\n${emitted}`).toEqual([]);

  return { first, second, emitted, warnings };
}

describe("argtype backend structural round-trip", () => {
  it("round-trips bet.argtype (terminals, constraints, defaults, outputs)", () => {
    const { first, second, warnings } = roundTrip(frontendFixture("bet.argtype"));
    expect(warnings).toEqual([]);
    expect(second.expr).toEqual(first.expr);
    expect(second.meta).toEqual(first.meta);
  });

  it("round-trips a subcommand union (alt arms with labels and a positional default)", () => {
    const { first, second, warnings } = roundTrip(fixture("subcommands.argtype"));
    expect(warnings).toEqual([]);
    // The command is `<exe> <alt>`: the executable literal from frontmatter is
    // prepended, followed by the subcommand alternative.
    expect(first.expr.kind).toBe("sequence");
    const nodes = first.expr.kind === "sequence" ? first.expr.attrs.nodes : [];
    expect(nodes[0]?.kind).toBe("literal");
    expect(nodes.some((n) => n.kind === "alternative")).toBe(true);
    expect(second.expr).toEqual(first.expr);
    expect(second.meta).toEqual(first.meta);
  });

  it("round-trips join micro-syntax and media types", () => {
    const { first, second, warnings } = roundTrip(fixture("microsyntax.argtype"));
    expect(warnings).toEqual([]);
    expect(second.expr).toEqual(first.expr);
    expect(second.meta).toEqual(first.meta);
  });

  it("is idempotent (emit -> parse -> emit produces identical text)", () => {
    for (const name of ["subcommands.argtype", "microsyntax.argtype"]) {
      const { emitted, second } = roundTrip(fixture(name));
      const reEmitted = generateArgtype(second.expr, second.meta).source;
      expect(reEmitted).toBe(emitted);
    }
  });
});
