import { describe, expect, it } from "vitest";
import { PythonBackend, generatePackageInit } from "./python.js";
import {
  alt,
  float,
  generate,
  generateCtx,
  int,
  lit,
  namedAlt,
  opt,
  path,
  rep,
  repJoin,
  seq,
  seqJoin,
  str,
} from "./test-helpers.js";

describe("Python generation - structure", () => {
  it("emits auto-generated header and styxdefs imports", () => {
    const code = generate(seq(lit("tool")));
    expect(code).toContain("# This file was auto generated by Styx.");
    expect(code).toContain("import dataclasses");
    expect(code).toContain("import typing");
    expect(code).toContain("from styxdefs import");
    expect(code).toContain("Runner");
    expect(code).toContain("Execution");
    expect(code).toContain("Metadata");
    expect(code).toContain("InputPathType");
    expect(code).toContain("get_global_runner");
  });

  it("emits metadata constant with Metadata type using tool-prefixed name", () => {
    const code = generate(seq(lit("bet")), {
      app: { id: "bet", doc: { title: "bet", description: "Brain extraction" } },
      package: { name: "fsl" },
    });
    expect(code).toContain("BET_METADATA = Metadata(");
    expect(code).toContain('id="bet"');
    expect(code).toContain('name="bet"');
    expect(code).toContain('package="fsl"');
  });

  it("emits wrapper function with tool-prefixed name", () => {
    const code = generate(seq(lit("tool"), str("input")), {
      app: { id: "my-tool" },
    });
    expect(code).toContain("def my_tool(");
    expect(code).toContain("runner = runner if runner is not None else get_global_runner()");
    expect(code).toContain("execution = runner.start_execution(MY_TOOL_METADATA)");
    expect(code).toContain("execution.params(params)");
    expect(code).toContain("execution.run(args)");
  });
});

describe("Python generation - type declarations", () => {
  it("generates TypedDict for struct with string field", () => {
    const code = generate(seq(lit("tool"), str("name")));
    expect(code).toMatch(/class \w+\(typing\.TypedDict\):/);
    expect(code).toContain("name: str");
  });

  it("generates TypedDict for struct with multiple scalar types", () => {
    const code = generate(seq(str("input"), int("count"), float("ratio")));
    expect(code).toContain("input: str");
    expect(code).toContain("count: int");
    expect(code).toContain("ratio: float");
  });

  it("maps path to InputPathType", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain("infile: InputPathType");
  });

  it("maps optional to nullable field", () => {
    const code = generate(seq(opt(str("name"))));
    expect(code).toMatch(/name: typing\.NotRequired\[str \| None\]/);
  });

  it("maps repeat to list type", () => {
    const code = generate(seq(rep(str("item"), "items")));
    expect(code).toContain("list[str]");
  });

  it("maps literal union (alternative of literals) to typing.Literal union", () => {
    const code = generate(seq(alt(lit("a"), lit("b"), lit("c"))));
    expect(code).toMatch(/typing\.Literal\["a"\]\s*\|\s*typing\.Literal\["b"\]/);
  });
});

describe("Python generation - TypedDict NotRequired (mypy cleanliness)", () => {
  // The params factory builds the initial dict literal with only required +
  // explicitly-defaulted fields, then conditionally adds optional-without-default
  // fields (`if x is not None: params["x"] = x`). Those conditionally-set fields
  // must be NotRequired in the TypedDict, or mypy flags "Missing keys" at the
  // factory's dict literal. The classification mirrors the factory exactly:
  // optional && !hasExplicitDefault.

  it("marks optional-without-default fields NotRequired", () => {
    const code = generate(seq(lit("t"), str("name"), opt(str("opt_name"))), { app: { id: "t" } });
    // Required field: bare, no NotRequired.
    expect(code).toMatch(/^ {4}name: str$/m);
    // Optional-without-default field: NotRequired.
    expect(code).toMatch(/opt_name: typing\.NotRequired\[str \| None\]/);
  });

  it("keeps explicitly-defaulted optional fields required (factory always writes them)", () => {
    const code = generate(
      seq(lit("t"), opt(seq(lit("-v")), { name: "verbose", defaultValue: false })),
      { app: { id: "t" } },
    );
    // Defaulted field is nullable but required - no NotRequired wrapper.
    expect(code).toMatch(/verbose: bool \| None/);
    expect(code).not.toMatch(/verbose: typing\.NotRequired/);
  });

  it("keeps required (non-optional, no default) fields required", () => {
    const code = generate(seq(lit("t"), str("name")), { app: { id: "t" } });
    expect(code).toMatch(/^ {4}name: str$/m);
    expect(code).not.toMatch(/name: typing\.NotRequired/);
  });

  it("marks optional list fields NotRequired", () => {
    const code = generate(seq(lit("t"), opt(rep(str("item"), "items"))), { app: { id: "t" } });
    expect(code).toMatch(/items: typing\.NotRequired\[list\[str\] \| None\]/);
  });

  it("marks optional fields NotRequired inside a functional-syntax TypedDict (non-ident key)", () => {
    // A `@type` discriminator forces the functional `TypedDict(...)` syntax; the
    // NotRequired wrapping must apply there too.
    const code = generate(seq(lit("bet"), opt(str("frac"))), {
      app: { id: "bet" },
      package: { name: "fsl" },
    });
    expect(code).toMatch(/"frac": typing\.NotRequired\[str \| None\]/);
  });

  it("binds NotRequired optional fields to a narrowed .get() local in cargs", () => {
    // Since the field is NotRequired, the factory omits it when None. The cargs
    // builder binds the value to a local read via `.get()` (a bare subscript would
    // KeyError when the caller omits the key) and reuses that local - one lookup,
    // absent-safe, and mypy can narrow it.
    const code = generate(seq(lit("t"), opt(seq(lit("-n"), int("nthreads")))), {
      app: { id: "t" },
    });
    const m = code.match(/(\w+) = params\.get\("nthreads"\)/);
    expect(m).toBeTruthy();
    const v = m![1];
    expect(code).toContain(`if ${v} is not None:`);
    expect(code).toContain(`cargs.append(str(${v}))`);
    // No re-subscript of the omittable key outside the factory's own conditional set.
    expect(code).not.toContain('cargs.append(str(params["nthreads"]))');
    // The factory genuinely omits the key (justifying the .get() read).
    expect(code).toMatch(/if nthreads is not None:\s*\n\s*params\["nthreads"\] = nthreads/);
  });
});

describe("Python generation - docstrings", () => {
  it("emits field docstring for fields with descriptions", () => {
    const code = generate(seq(str("input", "An important parameter")));
    expect(code).toContain('"""An important parameter"""');
  });

  it("emits wrapper docstring from app metadata", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "bet",
        doc: { title: "bet", description: "Brain extraction tool" },
      },
    });
    expect(code).toContain("Brain extraction tool");
    expect(code).toContain("Args:");
    expect(code).toContain("params: The parameters.");
    expect(code).toContain("runner: Command runner");
  });

  it("includes author and URL in wrapper docstring", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "tool",
        doc: {
          title: "tool",
          authors: ["Alice", "Bob"],
          urls: ["https://example.com"],
        },
      },
    });
    expect(code).toContain("Author: Alice, Bob");
    expect(code).toContain("URL: https://example.com");
  });

  it("emits docstring for optional scalar field (doc on inner terminal)", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--out"), str("output", "Output path")))));
    expect(code).toContain('"""Output path"""');
    expect(code).toMatch(/output: typing\.NotRequired\[str \| None\]/);
  });

  it("emits docstrings for fields inside repeat struct", () => {
    const code = generate(
      seq(
        lit("cmd"),
        rep(
          seq(
            str("name", "Entry name"),
            int({ name: "value", doc: { description: "Entry value" } }),
          ),
          "entries",
        ),
      ),
    );
    expect(code).toContain('"""Entry name"""');
    expect(code).toContain('"""Entry value"""');
  });
});

describe("Python generation - cargs building", () => {
  it("appends literal strings", () => {
    const code = generate(seq(lit("tool"), str("input")));
    expect(code).toContain('cargs.append("tool")');
  });

  it("appends string params directly (no str())", () => {
    const code = generate(seq(str("name")));
    expect(code).toContain('cargs.append(params["name"])');
  });

  it("wraps int params with str()", () => {
    const code = generate(seq(int("count")));
    expect(code).toContain('cargs.append(str(params["count"]))');
  });

  it("uses execution.input_file for path params", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain('cargs.append(execution.input_file(params["infile"]))');
  });

  it("binds optional params to a narrowed local read via .get() (key may be absent)", () => {
    const code = generate(seq(opt(str("name"))));
    const m = code.match(/(\w+) = params\.get\("name"\)/);
    expect(m).toBeTruthy();
    expect(code).toContain(`if ${m![1]} is not None:`);
  });

  it("emits truthy check for bool flags", () => {
    const code = generate(seq(opt(seq(lit("-v")))));
    expect(code).toMatch(/if params\["\w+"\]:/);
  });

  it("emits for-in loop for list params with correct loop variable", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    // Scope to the cargs function: the validate function also loops over the list.
    const cargs = code.slice(code.indexOf("def cargs("));
    const match = cargs.match(/for (\w+) in params\["vals"\]:/);
    expect(match).toBeTruthy();
    const itemVar = match![1];
    expect(cargs).toContain(`str(${itemVar})`);
  });

  it("emits range() loop for count params", () => {
    const code = generate(seq(rep(seq(lit("-v")), "verbosity")));
    expect(code).toMatch(/for _i\d+ in range\(/);
  });

  it("handles nested optional with flag and value", () => {
    const code = generate(seq(opt(seq(lit("-f"), float("threshold")))));
    // The optional binds a narrowed local via .get() (absent-safe, single lookup);
    // both the guard and the inner value read use that local.
    const m = code.match(/(\w+) = params\.get\("threshold"\)/);
    expect(m).toBeTruthy();
    const v = m![1];
    expect(code).toContain(`if ${v} is not None:`);
    expect(code).toContain('cargs.append("-f")');
    expect(code).toContain(`cargs.append(str(${v}))`);
  });

  it("handles literal union alternative as str() append", () => {
    const code = generate(seq(alt(lit("fast"), lit("slow"))));
    expect(code).toContain("cargs.append(str(params[");
  });
});

describe("Python generation - complex IR", () => {
  it("handles sequence with mixed required and optional fields", () => {
    const code = generate(
      seq(
        lit("tool"),
        str("input"),
        opt(seq(lit("--threshold"), float("threshold"))),
        opt(seq(lit("-v")), { name: "verbose", defaultValue: false }),
      ),
    );
    expect(code).toContain("input: str");
    // Optional-no-default -> NotRequired; defaulted optional (verbose) stays required.
    expect(code).toMatch(/threshold: typing\.NotRequired\[float \| None\]/);
    expect(code).toMatch(/verbose: bool \| None/);
    expect(code).toContain('cargs.append("tool")');
    expect(code).toContain('if params["verbose"]:');
  });

  it("handles repeat inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), rep(float("coord"), "coords")))));
    expect(code).toMatch(/coords: typing\.NotRequired\[list\[float\] \| None\]/);
    const m = code.match(/(\w+) = params\.get\("coords"\)/);
    expect(m).toBeTruthy();
    const v = m![1];
    expect(code).toContain(`if ${v} is not None:`);
    // The for-loop iterates the narrowed local, not a re-subscript.
    expect(code).toContain(`for item0 in ${v}:`);
  });

  it("handles alternative with non-literal variants (discriminated union)", () => {
    const code = generate(
      seq(alt(seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    // TypedDicts with @type emitted via functional syntax.
    expect(code).toContain('"@type": typing.Literal["variant_0"]');
    expect(code).toContain('"@type": typing.Literal["variant_1"]');
    expect(code).toMatch(/if .*\["@type"\] == "variant_0":/);
    expect(code).toMatch(/elif .*\["@type"\] == "variant_1":/);
  });

  it("handles deeply nested: seq > opt > seq > rep > int", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--dims"), rep(int("dim"), "dims")))));
    expect(code).toContain("list[int]");
    expect(code).toContain('cargs.append("--dims")');
  });
});

describe("Python generation - discriminated unions", () => {
  it("emits @type literal on each variant TypedDict via functional syntax", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    expect(code).toContain('"@type": typing.Literal["variant_0"]');
    expect(code).toContain('"file": InputPathType');
    expect(code).toContain('"@type": typing.Literal["variant_1"]');
    expect(code).toContain('"url": str');
  });

  it("emits union type alias referencing variant TypedDicts", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    expect(code).toMatch(/^\w+ = \w+ \| \w+$/m);
  });

  it("uses named variants when alt children have meta names", () => {
    const expr = seq({
      kind: "alternative" as const,
      attrs: {
        alts: [
          { ...seq(lit("--file"), path("file")), meta: { name: "by_file" } },
          { ...seq(lit("--url"), str("url")), meta: { name: "by_url" } },
        ],
      },
      meta: { name: "source" },
    });
    const code = generate(expr);
    expect(code).toContain('"@type": typing.Literal["by_file"]');
    expect(code).toContain('"@type": typing.Literal["by_url"]');
    expect(code).toMatch(/if params\["source"\]\["@type"\] == "by_file":/);
  });

  it("does not emit @type on literal union variant aliases", () => {
    const code = generate(seq(namedAlt("mode", lit("fast"), lit("slow"))));
    expect(code).not.toContain('"@type": typing.Literal["fast"]');
    expect(code).toMatch(/typing\.Literal\["fast"\]\s*\|\s*typing\.Literal\["slow"\]/);
  });

  it("emits correct cargs for each variant branch", () => {
    const code = generate(
      seq(
        lit("cmd"),
        namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url"))),
      ),
      { app: { id: "t" } },
    );
    expect(code).toContain('cargs.append("--file")');
    expect(code).toContain('execution.input_file(params["source"]["file"])');
    expect(code).toContain('cargs.append("--url")');
    expect(code).toContain('params["source"]["url"]');
  });

  // Regression (mrtrix dwi2response): a union variant contains a union-typed
  // field, and that inner union is shared across sibling variants. The inner
  // union is discovered deep under the FIRST variant but also referenced by a
  // LATER sibling - the old reverse-discovery emission ordered the later
  // variant's TypedDict BEFORE the inner union alias, so Python (eager type
  // evaluation) raised NameError at import and mypy flagged "used before
  // definition". The topological sort must declare every type after its
  // dependencies.
  it("orders a union-inside-union-variant alias before all of its users", () => {
    const wmAlgo = () => namedAlt("wm_algo", lit("fa"), lit("tax"), lit("tournier"));
    const code = generate(
      seq(
        lit("dwi2response"),
        namedAlt(
          "algorithm",
          // First variant discovers the inner `wm_algo` union deep.
          seq(lit("dhollander"), path("input"), opt(seq(lit("-wm_algo"), wmAlgo()))),
          seq(lit("fa"), path("input")),
          // A later sibling references the SAME (deduped) inner union.
          seq(lit("msmt_5tt"), path("input"), opt(seq(lit("-wm_algo"), wmAlgo()))),
        ),
      ),
      { app: { id: "dwi2response" } },
    );

    // The literal-union alias (e.g. Dwi2responseWmAlgo = Literal["fa"] | ...)
    // must be declared before every field that references it.
    const aliasName = code.match(/^(\w+) = typing\.Literal\["fa"\]/m)?.[1];
    expect(aliasName).toBeTruthy();
    const defIdx = code.indexOf(`${aliasName} = typing.Literal`);
    const refs = [...code.matchAll(new RegExp(`"wm_algo": typing\\.\\w+\\[${aliasName}`, "g"))];
    // dhollander + msmt_5tt both reference it.
    expect(refs.length).toBeGreaterThanOrEqual(2);
    for (const r of refs) expect(r.index!).toBeGreaterThan(defIdx);

    // The top-level discriminated-union alias (`Algorithm = A | B | ...`) must
    // come after every variant TypedDict it lists.
    const unionLine = code.match(/^(\w+) = (\w+(?: \| \w+)+)$/m);
    const unionFull = unionLine?.[0];
    const unionRhs = unionLine?.[2];
    expect(unionRhs).toBeTruthy();
    const unionIdx = code.indexOf(unionFull!);
    for (const variant of unionRhs!.split(" | ")) {
      const variantDef = code.search(
        new RegExp(
          `^(?:${variant} = typing\\.TypedDict|class ${variant}\\(typing\\.TypedDict)`,
          "m",
        ),
      );
      expect(variantDef).toBeGreaterThanOrEqual(0);
      expect(variantDef).toBeLessThan(unionIdx);
    }
  });

  // Regression: a mixed union (struct + bare-literal variants, e.g. ants
  // `Interpolation`) cannot dispatch with `params.x["@type"]` because the
  // literal arms aren't dicts. cargs must branch on runtime shape.
  it("emits a runtime-shape branch for mixed (struct + literal) unions", () => {
    const code = generate(
      seq(lit("cmd"), namedAlt("mode", lit("fast"), seq(lit("--full"), str("level")))),
      { app: { id: "t" } },
    );
    expect(code).toContain('if isinstance(params["mode"], dict):');
    expect(code).toContain('if params["mode"]["@type"] == "variant_1":');
    expect(code).toContain('cargs.append(str(params["mode"]))');
  });
});

describe("Python generation - public names / __all__", () => {
  it("emits tool-prefixed public names directly in the tool file", () => {
    const code = generate(seq(lit("bet"), str("input")), { app: { id: "bet" } });
    expect(code).toContain("class Bet(typing.TypedDict):");
    expect(code).toContain("BET_METADATA = Metadata(");
    expect(code).toContain("def bet_cargs(");
    expect(code).toContain("def bet(");
  });

  it("emits __all__ listing only the public names", () => {
    const code = generate(seq(lit("bet"), str("input")), { app: { id: "bet" } });
    expect(code).toMatch(/__all__ = \[[\s\S]*?\]/);
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).toContain('"Bet"');
    expect(allBlock).toContain('"BET_METADATA"');
    expect(allBlock).toContain('"bet"');
    expect(allBlock).not.toContain('"Params"');
    expect(allBlock).not.toContain('"METADATA"');
    expect(allBlock).not.toContain('"run"');
  });

  it("omits Outputs symbols from __all__ when no outputs are present", () => {
    const code = generate(seq(lit("bet"), path("input")), { app: { id: "bet" } });
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).not.toContain('"BetOutputs"');
    expect(allBlock).not.toContain('"bet_outputs"');
  });

  it("uses generic names when no appId is provided", () => {
    const code = generate(seq(lit("tool"), str("input")));
    expect(code).toContain("def run(");
    expect(code).toContain("def cargs(");
    expect(code).toContain("METADATA = Metadata(");
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).toContain('"Params"');
    expect(allBlock).toContain('"run"');
  });
});

describe("PythonBackend", () => {
  it("emits a single flat tool file keyed by snake_cased app id", () => {
    const ctx = generateCtx(seq(lit("bet"), str("input")), {
      app: { id: "bet", doc: { title: "bet" } },
    });
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.errors).toHaveLength(0);
    expect(result.files.has("bet.py")).toBe(true);
    expect(result.files.size).toBe(1);
    expect(result.files.get("bet.py")).toContain("def bet(");
  });

  it("snake-cases multi-word app ids in the tool file name", () => {
    const ctx = generateCtx(seq(lit("my-tool"), str("input")), {
      app: { id: "my-tool", doc: { title: "my-tool" } },
    });
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.files.has("my_tool.py")).toBe(true);
  });

  it("uses output.py when no app id", () => {
    const ctx = generateCtx(seq(str("input")));
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.files.has("output.py")).toBe(true);
  });

  it("emitPackage emits an __init__.py with star-imports of each tool module", () => {
    const backend = new PythonBackend();
    const apps = [
      backend.emitApp(generateCtx(seq(lit("bet"), str("input")), { app: { id: "bet" } })),
      backend.emitApp(generateCtx(seq(lit("flirt"), str("input")), { app: { id: "flirt" } })),
    ];
    const pkg = backend.emitPackage({ name: "fsl" }, apps);

    expect(pkg.files.has("__init__.py")).toBe(true);
    const init = pkg.files.get("__init__.py")!;
    expect(init).toContain("from .bet import *");
    expect(init).toContain("from .flirt import *");
  });

  it("generatePackageInit sorts modules alphabetically", () => {
    const init = generatePackageInit([
      { meta: { id: "zeta" }, files: new Map(), errors: [], warnings: [] },
      { meta: { id: "alpha" }, files: new Map(), errors: [], warnings: [] },
      { meta: { id: "mu" }, files: new Map(), errors: [], warnings: [] },
    ]);
    const idx = (s: string) => init.indexOf(s);
    expect(idx("from .alpha import *")).toBeLessThan(idx("from .mu import *"));
    expect(idx("from .mu import *")).toBeLessThan(idx("from .zeta import *"));
  });
});

describe("Python generation - params factory & kwarg wrapper", () => {
  it("emits a `<tool>_params` factory returning the params dict", () => {
    const code = generate(seq(lit("greet"), str("name", "Person to greet.")), {
      app: { id: "greet" },
    });
    expect(code).toMatch(/def greet_params\(\s*name: str,\s*\) -> Greet:/);
    expect(code).toContain('"name": name,');
    expect(code).toContain("return params");
  });

  it("renames the dict-style wrapper to `<tool>_execute`", () => {
    const code = generate(seq(lit("greet"), str("name")), { app: { id: "greet" } });
    expect(code).toContain("def greet_execute(params: Greet, runner: Runner | None = None)");
  });

  it("emits a kwarg `<tool>` wrapper that calls the factory then execute", () => {
    const code = generate(seq(lit("greet"), str("name")), { app: { id: "greet" } });
    expect(code).toMatch(/def greet\(\s*name: str,\s*runner: Runner \| None = None,\s*\) -> None:/);
    expect(code).toMatch(/params = greet_params\(\s*name=name,\s*\)/);
    expect(code).toContain("greet_execute(params, runner)");
  });

  it("renders explicit defaults in the kwarg signature; bool defaults stay required in dict", () => {
    const code = generate(
      seq(lit("t"), str("name"), opt(seq(lit("-v")), { name: "verbose", defaultValue: false })),
      { app: { id: "t" } },
    );
    // Signature: explicit default rendered.
    expect(code).toMatch(/verbose: bool = False/);
    // Body: required field included unconditionally in the dict literal.
    expect(code).toMatch(/"verbose": verbose,/);
  });

  it("conditionally adds optional-without-default fields to the dict", () => {
    const code = generate(seq(lit("t"), opt(str("name"))), { app: { id: "t" } });
    expect(code).toMatch(/name: str \| None = None,/);
    expect(code).toMatch(/if name is not None:/);
    expect(code).toMatch(/params\["name"\] = name/);
  });

  it("orders required (no default) before defaulted fields in the signature", () => {
    // `required_str` has no default; `flag` has explicit default false.
    const code = generate(
      seq(
        lit("t"),
        str("required_str"),
        opt(seq(lit("-v")), { name: "flag", defaultValue: false }),
      ),
      { app: { id: "t" } },
    );
    const sig = code.match(/def t_params\(([\s\S]*?)\) -> T:/)?.[1] ?? "";
    const requiredIdx = sig.indexOf("required_str:");
    const flagIdx = sig.indexOf("flag:");
    expect(requiredIdx).toBeGreaterThanOrEqual(0);
    expect(flagIdx).toBeGreaterThan(requiredIdx);
  });

  it("threads field docs into the Args block of both factory and kwarg wrapper", () => {
    const code = generate(seq(lit("t"), str("name", "Person to greet.")), { app: { id: "t" } });
    // Both functions emit `name: Person to greet.` under `Args:`.
    const docs = code.match(/name: Person to greet\./g) ?? [];
    expect(docs.length).toBeGreaterThanOrEqual(2);
  });

  it("wraps long field docs with `\\` continuation at ~80 cols", () => {
    const longDoc =
      "This is a very long description that should be wrapped at approximately eighty columns to keep the docstring readable in source.";
    const code = generate(seq(lit("t"), str("name", longDoc)), { app: { id: "t" } });
    expect(code).toContain("\\");
    // Continuation indented 8 spaces beneath `    name:`.
    expect(code).toMatch(/\n {8}\S+/);
  });

  it("injects `@type: NotRequired[Literal[<pkg>/<id>]]` on the root TypedDict + dict literal", () => {
    const code = generate(seq(lit("bet"), str("name")), {
      app: { id: "bet" },
      package: { name: "fsl" },
    });
    // TypedDict: NotRequired. Factory body: always written.
    expect(code).toContain('"@type": typing.NotRequired[typing.Literal["fsl/bet"]]');
    expect(code).toContain('"@type": "fsl/bet"');
  });

  it("skips the kwarg wrapper / factory when the solver leaves no struct root", () => {
    // A root-level alternative solves to a union (not a struct): no named fields
    // to spread into a factory/kwarg signature. (A single-field tool, by
    // contrast, is wrapped into a struct root and DOES get the kwarg path.)
    const code = generate(alt(seq(lit("a"), str("x")), seq(lit("b"), str("y"))), {
      app: { id: "t" },
    });
    expect(code).not.toMatch(/def t_params\(/);
    expect(code).not.toMatch(/def t_execute\(/);
    // The user-facing wrapper is still emitted as the dict-style fallback.
    expect(code).toMatch(/def t\(params:/);
  });

  it("wraps a single collapsed field into a struct root with the kwarg path", () => {
    // `--out=VALUE` collapses to a lone scalar; the root fixup wraps it in a
    // struct so the params dict has the field and the kwarg wrapper works.
    const code = generate(seq(seqJoin("=", lit("--out"), str("out"))), { app: { id: "t" } });
    expect(code).toMatch(/def t_params\(/);
    expect(code).toContain('params["out"]');
  });

  it("lists the new symbols in __all__", () => {
    const code = generate(seq(lit("bet"), str("name")), { app: { id: "bet" } });
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).toContain('"bet_params"');
    expect(allBlock).toContain('"bet_execute"');
    expect(allBlock).toContain('"bet"');
  });
});

describe("Python generation - join", () => {
  it("joins sequence parts into single arg with empty separator", () => {
    const code = generate(seq(opt(seqJoin("", lit("-f"), str("file")))));
    expect(code).toContain('"".join(');
  });

  it("joins sequence parts with comma separator", () => {
    const code = generate(seq(opt(seqJoin(",", str("x"), str("y")))));
    expect(code).toContain('",".join(');
  });

  it("joins repeat items via list comprehension and join", () => {
    const code = generate(seq(repJoin(",", int("val"), "vals")));
    expect(code).toContain('",".join([str(');
    expect(code).toContain(" for ");
    expect(code).toContain(" in ");
  });

  it("uses for-in loop when repeat has no join", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    expect(code).toMatch(/for \w+ in params\["vals"\]:/);
    expect(code).not.toContain(".join(");
  });

  it("handles optional wrapping a joined sequence", () => {
    const code = generate(seq(opt(seqJoin("=", lit("--output"), str("path")))));
    // Optional at statement level binds a narrowed local via .get(), then guards.
    const m = code.match(/(\w+) = params\.get\("path"\)/);
    expect(m).toBeTruthy();
    expect(code).toContain(`if ${m![1]} is not None:`);
    expect(code).toContain('"=".join(');
    const pushCount = (code.match(/cargs\.append/g) || []).length;
    expect(pushCount).toBe(1);
  });

  it("handles repeat with join inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), repJoin(",", float("coord"), "coords")))));
    const m = code.match(/(\w+) = params\.get\("coords"\)/);
    expect(m).toBeTruthy();
    expect(code).toContain(`if ${m![1]} is not None:`);
    expect(code).toContain('",".join(');
    expect(code).toContain('cargs.append("-c")');
  });

  it("handles joined sequence with path (uses execution.input_file)", () => {
    const code = generate(seq(seqJoin("=", lit("--input"), path("file"))));
    expect(code).toContain("execution.input_file");
    expect(code).toContain('"=".join(');
  });

  // Regression: bool/union alternatives inside a join used to emit if/else
  // statements directly into a `"".join([...])` list literal, producing
  // unparseable Python. They must collapse to a ternary expression.
  it("bool alternative inside seqJoin emits ternary, not if/else", () => {
    const code = generate(seq(seqJoin(",", lit("X"), namedAlt("flag", lit("0"), lit("1")))));
    // Stmt-shaped `if X:` inside the join argument is the bug. Ensure the join
    // arg uses ternary syntax instead.
    expect(code).toMatch(/"0" if params\["flag"\] else "1"/);
    expect(code).not.toMatch(/\.join\(\[[^\]]*if params\["flag"\]:/);
  });

  it("bool alternative inside optional seqJoin (antsRegistration use_inverse shape)", () => {
    const code = generate(
      seq(
        seqJoin(
          "",
          lit("["),
          path("infile"),
          opt(seqJoin("", lit(","), namedAlt("inv", lit("0"), lit("1")))),
          lit("]"),
        ),
      ),
    );
    // The optional wraps the inner seqJoin into a ternary inside the outer join.
    // A walrus binds the narrowed local read via .get() (key may be absent); the
    // lazy ternary only evaluates the inner expr (which uses the local) when present.
    const m = code.match(/\((\w+) := params\.get\("inv"\)\) is not None else ""/);
    expect(m).toBeTruthy();
    expect(code).toContain(`"0" if ${m![1]} else "1"`);
  });

  it("discriminated union with seqJoin variants inside seqJoin emits chained ternary", () => {
    // Variants must be Expr-shaped (seqJoin) to fold into a chained ternary.
    const code = generate(
      seq(
        seqJoin(
          ",",
          lit("X"),
          namedAlt("kind", seqJoin("=", lit("a"), str("v1")), seqJoin("=", lit("b"), str("v2"))),
        ),
      ),
    );
    expect(code).toMatch(/if params\["kind"\]\["@type"\] == "variant_0" else/);
    // Verify the chained-ternary form is used (no elif inside the join).
    expect(code).not.toMatch(/\.join\(\[[^\]]*elif /);
  });
});
