import { describe, expect, it } from "vitest";
import { PythonBackend, generatePackageInit } from "./python.js";
import {
  alt,
  float,
  generate,
  generateCtx,
  int,
  lit,
  namedAlt,
  opt,
  path,
  rep,
  repJoin,
  seq,
  seqJoin,
  str,
} from "./test-helpers.js";

describe("Python generation - structure", () => {
  it("emits auto-generated header and styxdefs imports", () => {
    const code = generate(seq(lit("tool")));
    expect(code).toContain("# This file was auto generated by Styx.");
    expect(code).toContain("import dataclasses");
    expect(code).toContain("import typing");
    expect(code).toContain("from styxdefs import");
    expect(code).toContain("Runner");
    expect(code).toContain("Execution");
    expect(code).toContain("Metadata");
    expect(code).toContain("InputPathType");
    expect(code).toContain("get_global_runner");
  });

  it("emits metadata constant with Metadata type using tool-prefixed name", () => {
    const code = generate(seq(lit("bet")), {
      app: { id: "bet", doc: { title: "bet", description: "Brain extraction" } },
      package: { name: "fsl" },
    });
    expect(code).toContain("BET_METADATA = Metadata(");
    expect(code).toContain('id="bet"');
    expect(code).toContain('name="bet"');
    expect(code).toContain('package="fsl"');
  });

  it("emits wrapper function with tool-prefixed name", () => {
    const code = generate(seq(lit("tool"), str("input")), {
      app: { id: "my-tool" },
    });
    expect(code).toContain("def my_tool(");
    expect(code).toContain("runner = runner if runner is not None else get_global_runner()");
    expect(code).toContain("execution = runner.start_execution(MY_TOOL_METADATA)");
    expect(code).toContain("execution.params(params)");
    expect(code).toContain("execution.run(args)");
  });
});

describe("Python generation - type declarations", () => {
  it("generates TypedDict for struct with string field", () => {
    const code = generate(seq(lit("tool"), str("name")));
    expect(code).toMatch(/class \w+\(typing\.TypedDict\):/);
    expect(code).toContain("name: str");
  });

  it("generates TypedDict for struct with multiple scalar types", () => {
    const code = generate(seq(str("input"), int("count"), float("ratio")));
    expect(code).toContain("input: str");
    expect(code).toContain("count: int");
    expect(code).toContain("ratio: float");
  });

  it("maps path to InputPathType", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain("infile: InputPathType");
  });

  it("maps optional to nullable field", () => {
    const code = generate(seq(opt(str("name"))));
    expect(code).toMatch(/name: str \| None/);
  });

  it("maps repeat to list type", () => {
    const code = generate(seq(rep(str("item"), "items")));
    expect(code).toContain("list[str]");
  });

  it("maps literal union (alternative of literals) to typing.Literal union", () => {
    const code = generate(seq(alt(lit("a"), lit("b"), lit("c"))));
    expect(code).toMatch(/typing\.Literal\["a"\]\s*\|\s*typing\.Literal\["b"\]/);
  });
});

describe("Python generation - docstrings", () => {
  it("emits field docstring for fields with descriptions", () => {
    const code = generate(seq(str("input", "An important parameter")));
    expect(code).toContain('"""An important parameter"""');
  });

  it("emits wrapper docstring from app metadata", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "bet",
        doc: { title: "bet", description: "Brain extraction tool" },
      },
    });
    expect(code).toContain("Brain extraction tool");
    expect(code).toContain("Args:");
    expect(code).toContain("params: The parameters.");
    expect(code).toContain("runner: Command runner");
  });

  it("includes author and URL in wrapper docstring", () => {
    const code = generate(seq(lit("tool")), {
      app: {
        id: "tool",
        doc: {
          title: "tool",
          authors: ["Alice", "Bob"],
          urls: ["https://example.com"],
        },
      },
    });
    expect(code).toContain("Author: Alice, Bob");
    expect(code).toContain("URL: https://example.com");
  });

  it("emits docstring for optional scalar field (doc on inner terminal)", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--out"), str("output", "Output path")))));
    expect(code).toContain('"""Output path"""');
    expect(code).toMatch(/output: str \| None/);
  });

  it("emits docstrings for fields inside repeat struct", () => {
    const code = generate(
      seq(
        lit("cmd"),
        rep(
          seq(
            str("name", "Entry name"),
            int({ name: "value", doc: { description: "Entry value" } }),
          ),
          "entries",
        ),
      ),
    );
    expect(code).toContain('"""Entry name"""');
    expect(code).toContain('"""Entry value"""');
  });
});

describe("Python generation - cargs building", () => {
  it("appends literal strings", () => {
    const code = generate(seq(lit("tool"), str("input")));
    expect(code).toContain('cargs.append("tool")');
  });

  it("appends string params directly (no str())", () => {
    const code = generate(seq(str("name")));
    expect(code).toContain('cargs.append(params["name"])');
  });

  it("wraps int params with str()", () => {
    const code = generate(seq(int("count")));
    expect(code).toContain('cargs.append(str(params["count"]))');
  });

  it("uses execution.input_file for path params", () => {
    const code = generate(seq(path("infile")));
    expect(code).toContain('cargs.append(execution.input_file(params["infile"]))');
  });

  it("emits is-not-None check for optional params", () => {
    const code = generate(seq(opt(str("name"))));
    expect(code).toContain('if params["name"] is not None:');
  });

  it("emits truthy check for bool flags", () => {
    const code = generate(seq(opt(seq(lit("-v")))));
    expect(code).toMatch(/if params\["\w+"\]:/);
  });

  it("emits for-in loop for list params with correct loop variable", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    const match = code.match(/for (\w+) in params\["vals"\]:/);
    expect(match).toBeTruthy();
    const itemVar = match![1];
    expect(code).toContain(`str(${itemVar})`);
  });

  it("emits range() loop for count params", () => {
    const code = generate(seq(rep(seq(lit("-v")), "verbosity")));
    expect(code).toMatch(/for _i\d+ in range\(/);
  });

  it("handles nested optional with flag and value", () => {
    const code = generate(seq(opt(seq(lit("-f"), float("threshold")))));
    expect(code).toContain('if params["threshold"] is not None:');
    expect(code).toContain('cargs.append("-f")');
    expect(code).toContain('cargs.append(str(params["threshold"]))');
  });

  it("handles literal union alternative as str() append", () => {
    const code = generate(seq(alt(lit("fast"), lit("slow"))));
    expect(code).toContain("cargs.append(str(params[");
  });
});

describe("Python generation - complex IR", () => {
  it("handles sequence with mixed required and optional fields", () => {
    const code = generate(
      seq(
        lit("tool"),
        str("input"),
        opt(seq(lit("--threshold"), float("threshold"))),
        opt(seq(lit("-v")), { name: "verbose", defaultValue: false }),
      ),
    );
    expect(code).toContain("input: str");
    expect(code).toMatch(/threshold: float \| None/);
    expect(code).toMatch(/verbose: bool \| None/);
    expect(code).toContain('cargs.append("tool")');
    expect(code).toContain('if params["verbose"]:');
  });

  it("handles repeat inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), rep(float("coord"), "coords")))));
    expect(code).toMatch(/coords: list\[float\] \| None/);
    expect(code).toContain('if params["coords"] is not None:');
    const match = code.match(/for (\w+) in params\["coords"\]:/);
    expect(match).toBeTruthy();
  });

  it("handles alternative with non-literal variants (discriminated union)", () => {
    const code = generate(seq(alt(seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))));
    // TypedDicts with @type emitted via functional syntax.
    expect(code).toContain('"@type": typing.Literal["variant_0"]');
    expect(code).toContain('"@type": typing.Literal["variant_1"]');
    expect(code).toMatch(/if .*\["@type"\] == "variant_0":/);
    expect(code).toMatch(/elif .*\["@type"\] == "variant_1":/);
  });

  it("handles deeply nested: seq > opt > seq > rep > int", () => {
    const code = generate(seq(lit("cmd"), opt(seq(lit("--dims"), rep(int("dim"), "dims")))));
    expect(code).toContain("list[int]");
    expect(code).toContain('cargs.append("--dims")');
  });
});

describe("Python generation - discriminated unions", () => {
  it("emits @type literal on each variant TypedDict via functional syntax", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    expect(code).toContain('"@type": typing.Literal["variant_0"]');
    expect(code).toContain('"file": InputPathType');
    expect(code).toContain('"@type": typing.Literal["variant_1"]');
    expect(code).toContain('"url": str');
  });

  it("emits union type alias referencing variant TypedDicts", () => {
    const code = generate(
      seq(namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url")))),
    );
    expect(code).toMatch(/^\w+ = \w+ \| \w+$/m);
  });

  it("uses named variants when alt children have meta names", () => {
    const expr = seq({
      kind: "alternative" as const,
      attrs: {
        alts: [
          { ...seq(lit("--file"), path("file")), meta: { name: "by_file" } },
          { ...seq(lit("--url"), str("url")), meta: { name: "by_url" } },
        ],
      },
      meta: { name: "source" },
    });
    const code = generate(expr);
    expect(code).toContain('"@type": typing.Literal["by_file"]');
    expect(code).toContain('"@type": typing.Literal["by_url"]');
    expect(code).toMatch(/if params\["source"\]\["@type"\] == "by_file":/);
  });

  it("does not emit @type on literal union variant aliases", () => {
    const code = generate(seq(namedAlt("mode", lit("fast"), lit("slow"))));
    expect(code).not.toContain('"@type": typing.Literal["fast"]');
    expect(code).toMatch(/typing\.Literal\["fast"\]\s*\|\s*typing\.Literal\["slow"\]/);
  });

  it("emits correct cargs for each variant branch", () => {
    const code = generate(
      seq(
        lit("cmd"),
        namedAlt("source", seq(lit("--file"), path("file")), seq(lit("--url"), str("url"))),
      ),
      { app: { id: "t" } },
    );
    expect(code).toContain('cargs.append("--file")');
    expect(code).toContain('execution.input_file(params["source"]["file"])');
    expect(code).toContain('cargs.append("--url")');
    expect(code).toContain('params["source"]["url"]');
  });
});

describe("Python generation - public names / __all__", () => {
  it("emits tool-prefixed public names directly in the tool file", () => {
    const code = generate(seq(lit("bet"), str("input")), { app: { id: "bet" } });
    expect(code).toContain("class Bet(typing.TypedDict):");
    expect(code).toContain("BET_METADATA = Metadata(");
    expect(code).toContain("def bet_cargs(");
    expect(code).toContain("def bet(");
  });

  it("emits __all__ listing only the public names", () => {
    const code = generate(seq(lit("bet"), str("input")), { app: { id: "bet" } });
    expect(code).toMatch(/__all__ = \[[\s\S]*?\]/);
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).toContain('"Bet"');
    expect(allBlock).toContain('"BET_METADATA"');
    expect(allBlock).toContain('"bet"');
    expect(allBlock).not.toContain('"Params"');
    expect(allBlock).not.toContain('"METADATA"');
    expect(allBlock).not.toContain('"run"');
  });

  it("omits Outputs symbols from __all__ when no outputs are present", () => {
    const code = generate(seq(lit("bet"), path("input")), { app: { id: "bet" } });
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).not.toContain('"BetOutputs"');
    expect(allBlock).not.toContain('"bet_outputs"');
  });

  it("uses generic names when no appId is provided", () => {
    const code = generate(seq(lit("tool"), str("input")));
    expect(code).toContain("def run(");
    expect(code).toContain("def cargs(");
    expect(code).toContain("METADATA = Metadata(");
    const allBlock = code.match(/__all__ = \[([\s\S]*?)\]/)?.[1] ?? "";
    expect(allBlock).toContain('"Params"');
    expect(allBlock).toContain('"run"');
  });
});

describe("PythonBackend", () => {
  it("emits a single flat tool file keyed by snake_cased app id", () => {
    const ctx = generateCtx(seq(lit("bet"), str("input")), {
      app: { id: "bet", doc: { title: "bet" } },
    });
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.errors).toHaveLength(0);
    expect(result.files.has("bet.py")).toBe(true);
    expect(result.files.size).toBe(1);
    expect(result.files.get("bet.py")).toContain("def bet(");
  });

  it("snake-cases multi-word app ids in the tool file name", () => {
    const ctx = generateCtx(seq(lit("my-tool"), str("input")), {
      app: { id: "my-tool", doc: { title: "my-tool" } },
    });
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.files.has("my_tool.py")).toBe(true);
  });

  it("uses output.py when no app id", () => {
    const ctx = generateCtx(seq(str("input")));
    const backend = new PythonBackend();
    const result = backend.emitApp(ctx);

    expect(result.files.has("output.py")).toBe(true);
  });

  it("emitPackage emits an __init__.py with star-imports of each tool module", () => {
    const backend = new PythonBackend();
    const apps = [
      backend.emitApp(generateCtx(seq(lit("bet"), str("input")), { app: { id: "bet" } })),
      backend.emitApp(generateCtx(seq(lit("flirt"), str("input")), { app: { id: "flirt" } })),
    ];
    const pkg = backend.emitPackage({ name: "fsl" }, apps);

    expect(pkg.files.has("__init__.py")).toBe(true);
    const init = pkg.files.get("__init__.py")!;
    expect(init).toContain("from .bet import *");
    expect(init).toContain("from .flirt import *");
  });

  it("generatePackageInit sorts modules alphabetically", () => {
    const init = generatePackageInit([
      { meta: { id: "zeta" }, files: new Map(), errors: [], warnings: [] },
      { meta: { id: "alpha" }, files: new Map(), errors: [], warnings: [] },
      { meta: { id: "mu" }, files: new Map(), errors: [], warnings: [] },
    ]);
    const idx = (s: string) => init.indexOf(s);
    expect(idx("from .alpha import *")).toBeLessThan(idx("from .mu import *"));
    expect(idx("from .mu import *")).toBeLessThan(idx("from .zeta import *"));
  });
});

describe("Python generation - join", () => {
  it("joins sequence parts into single arg with empty separator", () => {
    const code = generate(seq(opt(seqJoin("", lit("-f"), str("file")))));
    expect(code).toContain('"".join(');
  });

  it("joins sequence parts with comma separator", () => {
    const code = generate(seq(opt(seqJoin(",", str("x"), str("y")))));
    expect(code).toContain('",".join(');
  });

  it("joins repeat items via list comprehension and join", () => {
    const code = generate(seq(repJoin(",", int("val"), "vals")));
    expect(code).toContain('",".join([str(');
    expect(code).toContain(" for ");
    expect(code).toContain(" in ");
  });

  it("uses for-in loop when repeat has no join", () => {
    const code = generate(seq(rep(int("val"), "vals")));
    expect(code).toMatch(/for \w+ in params\["vals"\]:/);
    expect(code).not.toContain(".join(");
  });

  it("handles optional wrapping a joined sequence", () => {
    const code = generate(seq(opt(seqJoin("=", lit("--output"), str("path")))));
    expect(code).toContain('if params["path"] is not None:');
    expect(code).toContain('"=".join(');
    const pushCount = (code.match(/cargs\.append/g) || []).length;
    expect(pushCount).toBe(1);
  });

  it("handles repeat with join inside optional", () => {
    const code = generate(seq(opt(seq(lit("-c"), repJoin(",", float("coord"), "coords")))));
    expect(code).toContain('if params["coords"] is not None:');
    expect(code).toContain('",".join(');
    expect(code).toContain('cargs.append("-c")');
  });

  it("handles joined sequence with path (uses execution.input_file)", () => {
    const code = generate(seq(seqJoin("=", lit("--input"), path("file"))));
    expect(code).toContain("execution.input_file");
    expect(code).toContain('"=".join(');
  });
});
