import type { AppMeta } from "../../ir/index.js";
import type { CodegenContext, PackageMeta } from "../../manifest/index.js";
import type { Backend, EmittedApp, EmittedPackage } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { Scope } from "../scope.js";
import { pascalCase, screamingSnakeCase, snakeCase } from "../string-case.js";
import { buildSigEntries } from "../sig-entries.js";
import {
  emitBuildCargs,
  emitImports,
  emitKwargWrapper,
  emitMetadata,
  emitParamsFactory,
  emitTypeDeclarations,
  emitWrapperFunction,
  pySigOptions,
} from "./emit.js";
import { collectFieldInfo } from "./types.js";
import {
  emitBuildOutputs,
  emitOutputsClass,
  emitStripExtensionsHelper,
  hasAnyOutputs,
  needsStripExtensionsHelper,
} from "./outputs-emit.js";
import { mapType } from "./typemap.js";
import { collectNamedTypes, resolveTypeName, structKey, unionKey } from "./types.js";

// Python reserved words + commonly-shadowed built-ins. Used to avoid collisions
// when generating identifiers.
const PY_RESERVED = [
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
  // Common builtins to avoid shadowing.
  "list",
  "dict",
  "tuple",
  "set",
  "int",
  "float",
  "str",
  "bool",
  "type",
  "print",
  "open",
  "input",
  "range",
  "len",
  "id",
  "object",
  "Exception",
  "ValueError",
  "TypeError",
  // styxdefs symbols we emit/import.
  "Runner",
  "Execution",
  "Metadata",
  "InputPathType",
  "OutputPathType",
  "get_global_runner",
  "dataclasses",
  "typing",
];

/**
 * Per-tool public symbol names. With the flat `fsl/bet.py` layout each tool
 * file emits these names directly - there is no internal/public alias split.
 */
export interface PublicNames {
  params: string;
  outputs: string;
  metadata: string;
  cargs: string;
  outputsFn: string;
  paramsFn: string;
  execute: string;
  wrapper: string;
}

/** Public-name scheme used by the Python backend. Exported so the CLI and tests can use it. */
export function computePublicNames(appId: string | undefined): PublicNames {
  if (!appId) {
    return {
      params: "Params",
      outputs: "Outputs",
      metadata: "METADATA",
      cargs: "cargs",
      outputsFn: "outputs",
      paramsFn: "build_params",
      execute: "execute",
      wrapper: "run",
    };
  }
  return {
    params: pascalCase(appId),
    outputs: pascalCase(appId) + "Outputs",
    metadata: screamingSnakeCase(appId) + "_METADATA",
    cargs: snakeCase(appId) + "_cargs",
    outputsFn: snakeCase(appId) + "_outputs",
    paramsFn: snakeCase(appId) + "_params",
    execute: snakeCase(appId) + "_execute",
    wrapper: snakeCase(appId),
  };
}

export function generatePython(ctx: CodegenContext): string {
  const cb = new CodeBuilder("    ");
  const scope = new Scope(PY_RESERVED);

  const appId = ctx.app?.id;
  const pkg = ctx.package?.name;
  const publicNames = computePublicNames(appId);

  const rootBinding = ctx.resolve(ctx.expr);
  const rootType = rootBinding?.type ?? { kind: "struct" as const, fields: {} };
  // Only treat the root as struct-shaped when there's a real binding. A
  // synthesized empty-struct fallback (no root binding) means the solver
  // collapsed everything away, so the kwarg wrapper has nothing to wrap.
  const rootIsStruct = rootBinding?.type.kind === "struct";

  // Pre-reserve module-level public names so any IR-derived names colliding
  // with them get suffix-bumped. `params` is intentionally NOT pre-reserved -
  // `collectNamedTypes` claims it for the root struct just below.
  const names = {
    params: publicNames.params,
    outputs: scope.add(publicNames.outputs),
    metadata: scope.add(publicNames.metadata),
    cargs: scope.add(publicNames.cargs),
    outputsFn: scope.add(publicNames.outputsFn),
    paramsFn: rootIsStruct ? scope.add(publicNames.paramsFn) : "",
    execute: rootIsStruct ? scope.add(publicNames.execute) : "",
    wrapper: scope.add(publicNames.wrapper),
  };

  const { namedTypes, typeDecls } = collectNamedTypes(rootType, names.params, scope, pascalCase);

  names.params =
    (rootType.kind === "struct" ? namedTypes.get(structKey(rootType)) : undefined) ??
    (rootType.kind === "union" ? namedTypes.get(unionKey(rootType)) : undefined) ??
    names.params;

  // Tag injected as `@type: Literal[...]` on the root TypedDict (and as a
  // constant key by the params factory). Skipped when appId/pkg aren't known.
  const rootTypeTag = appId && pkg ? `${pkg}/${appId}` : undefined;

  // Auto-generated header.
  cb.comment("This file was auto generated by Styx.", "# ");
  cb.comment("Do not edit this file directly.", "# ");
  cb.blank();

  const emitOutputs = hasAnyOutputs(ctx);

  emitImports(cb, emitOutputs);
  cb.blank();

  emitMetadata(ctx, names.metadata, cb);
  cb.blank();

  emitTypeDeclarations(typeDecls, namedTypes, ctx, cb, names.params, rootTypeTag);

  if (emitOutputs) {
    emitOutputsClass(ctx, names.outputs, cb);
    cb.blank();
  }

  const paramsType =
    rootType.kind === "struct" || rootType.kind === "union"
      ? names.params
      : mapType(rootType, resolveTypeName(namedTypes));

  if (emitOutputs && needsStripExtensionsHelper(ctx)) {
    emitStripExtensionsHelper(cb);
    cb.blank();
  }

  // Build the per-field SigEntry list once - the factory and kwarg wrapper
  // both consume it. `rootType` is narrowed by `rootIsStruct` for the
  // `Extract` constraint.
  const sigEntries =
    rootIsStruct && rootType.kind === "struct"
      ? buildSigEntries(
          rootType,
          collectFieldInfo(ctx, rootType),
          pySigOptions(resolveTypeName(namedTypes)),
        )
      : [];

  // Params factory (struct-rooted tools only): a kwarg-style builder for the
  // params dict. Useful for callers that want to build a dict to mutate before
  // executing.
  if (rootIsStruct) {
    emitParamsFactory(sigEntries, names.paramsFn, paramsType, rootTypeTag, cb);
    cb.blank();
  }

  emitBuildCargs(ctx, rootType, paramsType, names.cargs, cb);
  cb.blank();

  if (emitOutputs) {
    emitBuildOutputs(ctx, paramsType, names.outputs, names.outputsFn, cb);
    cb.blank();
  }

  // Dict-style execute function. For struct roots it's the internal
  // `<tool>_execute`; for other roots it doubles as the user-facing wrapper.
  const executeName = rootIsStruct ? names.execute : names.wrapper;
  emitWrapperFunction(
    ctx,
    paramsType,
    executeName,
    names.metadata,
    names.cargs,
    emitOutputs ? names.outputsFn : undefined,
    emitOutputs ? names.outputs : undefined,
    cb,
  );
  cb.blank();

  // Kwarg-style wrapper (struct roots only): the v1-parity user-facing entry.
  if (rootIsStruct) {
    emitKwargWrapper(
      ctx,
      sigEntries,
      names.wrapper,
      names.paramsFn,
      names.execute,
      emitOutputs ? names.outputs : undefined,
      cb,
    );
    cb.blank();
  }

  // `__all__` keeps suite-level `from .bet import *` from re-exporting the
  // module's stdlib/styxdefs imports.
  const publicSymbols = [
    names.params,
    ...(emitOutputs ? [names.outputs] : []),
    names.metadata,
    names.cargs,
    ...(emitOutputs ? [names.outputsFn] : []),
    ...(rootIsStruct ? [names.paramsFn, names.execute] : []),
    names.wrapper,
  ];
  cb.line("__all__ = [");
  cb.indent(() => {
    for (const sym of publicSymbols) cb.line(`"${sym}",`);
  });
  cb.line("]");

  return cb.toString();
}

/** Module name (file stem) for an app: snake_case of app.id, fallback `output`. */
export function appModuleName(meta: AppMeta | undefined): string {
  return meta?.id ? snakeCase(meta.id) : "output";
}

/**
 * Generate the suite-level `__init__.py` re-export for a package containing
 * multiple tool modules. Each tool module's public symbols are surfaced via
 * `from .bet import *` (each tool file defines `__all__`).
 */
export function generatePackageInit(apps: EmittedApp[]): string {
  const cb = new CodeBuilder("    ");
  cb.comment("This file was auto generated by Styx.", "# ");
  cb.comment("Do not edit this file directly.", "# ");
  cb.blank();

  const modules = apps
    .map((a) => appModuleName(a.meta))
    .filter((name): name is string => !!name)
    .sort();

  for (const mod of modules) {
    cb.line(`from .${mod} import *`);
  }

  return cb.toString();
}

export class PythonBackend implements Backend {
  readonly name = "python";
  readonly target = "python";

  emitApp(ctx: CodegenContext): EmittedApp {
    const code = generatePython(ctx);
    const fileName = `${appModuleName(ctx.app)}.py`;
    return {
      meta: ctx.app,
      files: new Map([[fileName, code]]),
      errors: [],
      warnings: [],
    };
  }

  emitPackage(pkg: PackageMeta, apps: EmittedApp[]): EmittedPackage {
    return {
      meta: pkg,
      files: new Map([["__init__.py", generatePackageInit(apps)]]),
      errors: [],
      warnings: [],
    };
  }
}
