import type { CodegenContext } from "../../manifest/index.js";
import type { Backend, EmitResult } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { Scope } from "../scope.js";
import { pascalCase, screamingSnakeCase, snakeCase } from "../string-case.js";
import {
  emitBuildCargs,
  emitImports,
  emitMetadata,
  emitTypeDeclarations,
  emitWrapperFunction,
} from "./emit.js";
import {
  emitBuildOutputs,
  emitOutputsClass,
  emitStripExtensionsHelper,
  hasAnyOutputs,
  needsStripExtensionsHelper,
} from "./outputs-emit.js";
import { mapType } from "./typemap.js";
import { collectNamedTypes, resolveTypeName, structKey, unionKey } from "./types.js";

// Python reserved words + commonly-shadowed built-ins. Used to avoid collisions
// when generating identifiers.
const PY_RESERVED = [
  "False",
  "None",
  "True",
  "and",
  "as",
  "assert",
  "async",
  "await",
  "break",
  "class",
  "continue",
  "def",
  "del",
  "elif",
  "else",
  "except",
  "finally",
  "for",
  "from",
  "global",
  "if",
  "import",
  "in",
  "is",
  "lambda",
  "nonlocal",
  "not",
  "or",
  "pass",
  "raise",
  "return",
  "try",
  "while",
  "with",
  "yield",
  // Common builtins to avoid shadowing.
  "list",
  "dict",
  "tuple",
  "set",
  "int",
  "float",
  "str",
  "bool",
  "type",
  "print",
  "open",
  "input",
  "range",
  "len",
  "id",
  "object",
  "Exception",
  "ValueError",
  "TypeError",
  // styxdefs symbols we emit/import. `Outputs` is omitted because we claim it
  // ourselves for the dataclass below; if an IR-derived type wants the same
  // name, the scope will bump it.
  "Runner",
  "Execution",
  "Metadata",
  "InputPathType",
  "OutputPathType",
  "get_global_runner",
  "dataclasses",
  "typing",
];

export interface GeneratedPython {
  /** Body of `<pkg>/_core.py` - all the implementation in generic-name form. */
  core: string;
  /** Body of `<pkg>/__init__.py` - rename-imports + `__all__`. */
  init: string;
}

export function generatePython(ctx: CodegenContext): GeneratedPython {
  const cb = new CodeBuilder("    ");
  const scope = new Scope(PY_RESERVED);

  const appId = ctx.app?.id;

  const rootBinding = ctx.resolve(ctx.expr);
  const rootType = rootBinding?.type ?? { kind: "struct" as const, fields: {} };

  // Pre-reserve internal generic names that are emitted unconditionally. The
  // module body always uses these so the structure is uniform across tools;
  // tool-specific names appear only as public aliases (under `__all__`) at
  // the bottom of the file. `Params` is NOT pre-reserved - `collectNamedTypes`
  // claims it for the root struct below.
  const internal = {
    params: "Params",
    outputs: scope.add("Outputs"),
    metadata: scope.add("METADATA"),
    cargs: scope.add("cargs"),
    outputsFn: scope.add("outputs"),
    wrapper: scope.add("run"),
  };

  const { namedTypes, typeDecls } = collectNamedTypes(
    rootType,
    internal.params,
    scope,
    pascalCase,
  );

  // Use whatever name collectNamedTypes ended up assigning (in case of a
  // name collision the root could have been bumped).
  internal.params =
    (rootType.kind === "struct" ? namedTypes.get(structKey(rootType)) : undefined) ??
    (rootType.kind === "union" ? namedTypes.get(unionKey(rootType)) : undefined) ??
    internal.params;

  const publicNames = {
    params: appId ? pascalCase(appId) : internal.params,
    outputs: appId ? pascalCase(appId) + "Outputs" : internal.outputs,
    metadata: appId ? screamingSnakeCase(appId) + "_METADATA" : internal.metadata,
    cargs: appId ? snakeCase(appId) + "_cargs" : internal.cargs,
    outputsFn: appId ? snakeCase(appId) + "_outputs" : internal.outputsFn,
    wrapper: appId ? snakeCase(appId) : internal.wrapper,
  };

  // Auto-generated header.
  cb.comment("This file was auto generated by Styx.", "# ");
  cb.comment("Do not edit this file directly.", "# ");
  cb.blank();

  const emitOutputs = hasAnyOutputs(ctx);

  emitImports(cb, emitOutputs);
  cb.blank();

  emitMetadata(ctx, internal.metadata, cb);
  cb.blank();

  emitTypeDeclarations(typeDecls, namedTypes, ctx, cb);

  if (emitOutputs) {
    emitOutputsClass(ctx, cb);
    cb.blank();
  }

  const paramsType =
    rootType.kind === "struct" || rootType.kind === "union"
      ? internal.params
      : mapType(rootType, resolveTypeName(namedTypes));

  if (emitOutputs && needsStripExtensionsHelper(ctx)) {
    emitStripExtensionsHelper(cb);
    cb.blank();
  }

  emitBuildCargs(ctx, rootType, paramsType, internal.cargs, cb);
  cb.blank();

  if (emitOutputs) {
    emitBuildOutputs(ctx, paramsType, internal.outputsFn, cb);
    cb.blank();
  }

  emitWrapperFunction(
    ctx,
    paramsType,
    internal.wrapper,
    internal.metadata,
    internal.cargs,
    emitOutputs ? internal.outputsFn : undefined,
    cb,
  );
  cb.blank();

  return {
    core: cb.toString(),
    init: generateInit(internal, publicNames, emitOutputs),
  };
}

/**
 * Build the `__init__.py` content - a tiny re-export module that imports
 * names from `_core` under their tool-prefixed aliases and declares them
 * in `__all__`.
 */
function generateInit(
  internal: PublicSwap,
  publicNames: PublicSwap,
  emitOutputs: boolean,
): string {
  const cb = new CodeBuilder("    ");
  cb.comment("This file was auto generated by Styx.", "# ");
  cb.comment("Do not edit this file directly.", "# ");
  cb.blank();

  const pairs: Array<[string, string]> = [
    [publicNames.params, internal.params],
    ...(emitOutputs
      ? ([[publicNames.outputs, internal.outputs]] as Array<[string, string]>)
      : []),
    [publicNames.metadata, internal.metadata],
    [publicNames.cargs, internal.cargs],
    ...(emitOutputs
      ? ([[publicNames.outputsFn, internal.outputsFn]] as Array<[string, string]>)
      : []),
    [publicNames.wrapper, internal.wrapper],
  ];

  cb.line("from ._core import (");
  cb.indent(() => {
    for (const [publicName, internalName] of pairs) {
      if (publicName === internalName) {
        cb.line(`${internalName},`);
      } else {
        cb.line(`${internalName} as ${publicName},`);
      }
    }
  });
  cb.line(")");
  cb.blank();

  cb.line("__all__ = [");
  cb.indent(() => {
    for (const [publicName] of pairs) {
      cb.line(`"${publicName}",`);
    }
  });
  cb.line("]");

  return cb.toString();
}

interface PublicSwap {
  params: string;
  outputs: string;
  metadata: string;
  cargs: string;
  outputsFn: string;
  wrapper: string;
}

export class PythonBackend implements Backend {
  readonly name = "python";
  readonly target = "python";

  emit(ctx: CodegenContext): EmitResult {
    const { core, init } = generatePython(ctx);
    const pkg = ctx.app?.id ? snakeCase(ctx.app.id) : "output";
    return {
      files: new Map([
        [`${pkg}/__init__.py`, init],
        [`${pkg}/_core.py`, core],
      ]),
      errors: [],
      warnings: [],
    };
  }
}
