import type { ProjectMeta } from "../../manifest/index.js";
import type { EmittedPackage } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { STYXDEFS_COMPAT } from "../styxdefs-compat.js";

function description(proj: ProjectMeta): string {
  if (proj.doc?.description) return proj.doc.description;
  return `Styx generated wrappers for ${proj.doc?.title ?? proj.name ?? "tools"}.`;
}

/** npm names must be lowercase and URL-safe; normalize or fall back. */
function npmName(name: string | undefined): string {
  const normalized = (name ?? "")
    .toLowerCase()
    .replace(/[^a-z0-9-._]/g, "-")
    .replace(/^[-._]+/, "");
  return normalized || "styx-wrappers";
}

/**
 * Single npm `package.json` for the whole project (TypeScript ships one package
 * spanning all suites, unlike Python's per-suite distributions). The styxdefs
 * floor is baked in as the lone runtime dependency.
 */
export function generatePackageJson(proj: ProjectMeta): string {
  const pkg = {
    name: npmName(proj.name),
    version: proj.version ?? "0.0.0",
    description: description(proj),
    type: "module",
    types: "./dist/index.d.ts",
    main: "./dist/index.js",
    exports: {
      ".": {
        types: "./dist/index.d.ts",
        import: "./dist/index.js",
      },
    },
    files: ["dist"],
    scripts: {
      build: "tsc",
      prepublishOnly: "npm run build",
    },
    license: proj.license?.description ?? "unknown",
    dependencies: {
      styxdefs: STYXDEFS_COMPAT.npm,
    },
    devDependencies: {
      typescript: "^5.6.0",
    },
  };
  return JSON.stringify(pkg, null, 2) + "\n";
}

/** Turn a suite directory name into a valid JS namespace identifier. */
function nsIdent(name: string): string {
  const cleaned = name.replace(/[^a-zA-Z0-9_$]/g, "_");
  return /^[0-9]/.test(cleaned) ? `_${cleaned}` : cleaned;
}

/**
 * Root barrel namespacing each per-suite `index.ts` by suite
 * (`export * as afni from "./afni/index.js"`). Namespacing avoids cross-suite
 * collisions when the same tool id appears in two suites, and keeps the root
 * from flattening every tool into one giant namespace.
 */
export function generateRootIndex(packages: EmittedPackage[]): string {
  const cb = new CodeBuilder("  ");
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  const dirs = packages
    .map((p) => p.meta?.name)
    .filter((name): name is string => !!name)
    .sort();

  for (const dir of dirs) {
    cb.line(`export * as ${nsIdent(dir)} from "./${dir}/index.js";`);
  }

  return cb.toString() + "\n";
}

/** Minimal `tsconfig.json` producing ESM + declarations into `dist/`. */
export function generateTsconfig(): string {
  const config = {
    compilerOptions: {
      target: "ES2020",
      module: "NodeNext",
      moduleResolution: "NodeNext",
      declaration: true,
      outDir: "./dist",
      strict: true,
      esModuleInterop: true,
      skipLibCheck: true,
      forceConsistentCasingInFileNames: true,
    },
    include: ["**/*.ts"],
    exclude: ["dist", "node_modules"],
  };
  return JSON.stringify(config, null, 2) + "\n";
}
