import type { AppMeta } from "../../ir/index.js";
import type { CodegenContext, PackageMeta } from "../../manifest/index.js";
import type { Backend, EmittedApp, EmittedPackage } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { Scope } from "../scope.js";
import { camelCase, pascalCase, screamingSnakeCase, snakeCase } from "../string-case.js";
import {
  emitBuildCargs,
  emitImports,
  emitMetadata,
  emitTypeDeclarations,
  emitWrapperFunction,
} from "./emit.js";
import {
  emitBuildOutputs,
  emitOutputsInterface,
  emitStripExtensionsHelper,
  hasAnyOutputs,
  needsStripExtensionsHelper,
} from "./outputs-emit.js";
import { mapType } from "./typemap.js";
import { collectNamedTypes, resolveTypeName, structKey, unionKey } from "./types.js";

const TS_RESERVED = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "let",
  "static",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "type",
];

/**
 * Per-tool public symbol names emitted directly in the flat tool file. Wrapper
 * and function names use camelCase; type names use PascalCase; the metadata
 * constant uses SCREAMING_SNAKE_CASE.
 */
export interface PublicNames {
  params: string;
  outputs: string;
  metadata: string;
  cargs: string;
  outputsFn: string;
  wrapper: string;
}

/** Public-name scheme used by the TypeScript backend. Exported so the CLI and tests can use it. */
export function computePublicNames(appId: string | undefined): PublicNames {
  if (!appId) {
    return {
      params: "Params",
      outputs: "Outputs",
      metadata: "METADATA",
      cargs: "cargs",
      outputsFn: "outputs",
      wrapper: "run",
    };
  }
  return {
    params: pascalCase(appId),
    outputs: pascalCase(appId) + "Outputs",
    metadata: screamingSnakeCase(appId) + "_METADATA",
    cargs: camelCase(appId) + "_cargs",
    outputsFn: camelCase(appId) + "_outputs",
    wrapper: camelCase(appId),
  };
}

export function generateTypeScript(ctx: CodegenContext): string {
  const cb = new CodeBuilder("  ");
  const scope = new Scope(TS_RESERVED);

  const appId = ctx.app?.id;
  const pkg = ctx.package?.name ?? "unknown";
  const publicNames = computePublicNames(appId);

  const rootBinding = ctx.resolve(ctx.expr);
  const rootType = rootBinding?.type ?? { kind: "struct" as const, fields: {} };

  // Pre-reserve module-level public names so any IR-derived names colliding
  // with them get suffix-bumped. `params` is intentionally NOT pre-reserved -
  // `collectNamedTypes` claims it for the root struct just below.
  const names = {
    params: publicNames.params,
    outputs: scope.add(publicNames.outputs),
    metadata: scope.add(publicNames.metadata),
    cargs: scope.add(publicNames.cargs),
    outputsFn: scope.add(publicNames.outputsFn),
    wrapper: scope.add(publicNames.wrapper),
  };

  const { namedTypes, typeDecls } = collectNamedTypes(rootType, names.params, scope, pascalCase);

  const rootName =
    (rootType.kind === "struct" ? namedTypes.get(structKey(rootType)) : undefined) ??
    (rootType.kind === "union" ? namedTypes.get(unionKey(rootType)) : undefined) ??
    names.params;
  names.params = rootName;

  // Auto-generated header.
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  const emitOutputs = hasAnyOutputs(ctx);

  emitImports(cb, emitOutputs);
  cb.blank();

  emitMetadata(ctx, names.metadata, cb);
  cb.blank();

  emitTypeDeclarations(typeDecls, namedTypes, ctx, names.params, appId, pkg, cb);

  if (emitOutputs) {
    emitOutputsInterface(ctx, names.outputs, cb);
    cb.blank();
  }

  const paramsType =
    rootType.kind === "struct" || rootType.kind === "union"
      ? names.params
      : mapType(rootType, resolveTypeName(namedTypes));

  if (emitOutputs && needsStripExtensionsHelper(ctx)) {
    emitStripExtensionsHelper(cb);
    cb.blank();
  }

  emitBuildCargs(ctx, rootType, paramsType, names.cargs, cb);
  cb.blank();

  if (emitOutputs) {
    emitBuildOutputs(ctx, paramsType, names.outputs, names.outputsFn, cb);
    cb.blank();
  }

  emitWrapperFunction(
    ctx,
    paramsType,
    names.wrapper,
    names.metadata,
    names.cargs,
    emitOutputs ? names.outputsFn : undefined,
    emitOutputs ? names.outputs : undefined,
    cb,
  );
  cb.blank();

  return cb.toString();
}

/** Module name (file stem) for an app: snake_case of app.id, fallback `output`. */
export function appModuleName(meta: AppMeta | undefined): string {
  return meta?.id ? snakeCase(meta.id) : "output";
}

/**
 * Generate the suite-level `index.ts` re-export for a package containing
 * multiple tool modules. Each tool module's public symbols are surfaced via
 * `export * from "./bet.js"`.
 */
export function generatePackageIndex(apps: EmittedApp[]): string {
  const cb = new CodeBuilder("  ");
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  const modules = apps
    .map((a) => appModuleName(a.meta))
    .filter((name): name is string => !!name)
    .sort();

  for (const mod of modules) {
    cb.line(`export * from "./${mod}.js";`);
  }

  return cb.toString();
}

export class TypeScriptBackend implements Backend {
  readonly name = "typescript";
  readonly target = "typescript";

  emitApp(ctx: CodegenContext): EmittedApp {
    const code = generateTypeScript(ctx);
    const fileName = `${appModuleName(ctx.app)}.ts`;
    return {
      meta: ctx.app,
      files: new Map([[fileName, code]]),
      errors: [],
      warnings: [],
    };
  }

  emitPackage(pkg: PackageMeta, apps: EmittedApp[]): EmittedPackage {
    return {
      meta: pkg,
      files: new Map([["index.ts", generatePackageIndex(apps)]]),
      errors: [],
      warnings: [],
    };
  }
}
