import type { CodegenContext } from "../../manifest/index.js";
import type { Backend, EmitResult } from "../backend.js";
import { CodeBuilder } from "../code-builder.js";
import { Scope } from "../scope.js";
import { camelCase, pascalCase, screamingSnakeCase } from "../string-case.js";
import {
  emitBuildCargs,
  emitImports,
  emitMetadata,
  emitTypeDeclarations,
  emitWrapperFunction,
} from "./emit.js";
import {
  emitBuildOutputs,
  emitOutputsInterface,
  emitStripExtensionsHelper,
  hasAnyOutputs,
  needsStripExtensionsHelper,
} from "./outputs-emit.js";
import { mapType } from "./typemap.js";
import { collectNamedTypes, resolveTypeName, structKey, unionKey } from "./types.js";

const TS_RESERVED = [
  "break",
  "case",
  "catch",
  "class",
  "const",
  "continue",
  "debugger",
  "default",
  "delete",
  "do",
  "else",
  "enum",
  "export",
  "extends",
  "false",
  "finally",
  "for",
  "function",
  "if",
  "import",
  "in",
  "instanceof",
  "new",
  "null",
  "return",
  "super",
  "switch",
  "this",
  "throw",
  "true",
  "try",
  "typeof",
  "undefined",
  "var",
  "void",
  "while",
  "with",
  "yield",
  "let",
  "static",
  "implements",
  "interface",
  "package",
  "private",
  "protected",
  "public",
  "type",
];

export interface GeneratedTypeScript {
  /** Body of `<pkg>/core.ts` - all the implementation in generic-name form. */
  core: string;
  /** Body of `<pkg>/index.ts` - rename re-exports of `core.ts`. */
  index: string;
}

export function generateTypeScript(ctx: CodegenContext): GeneratedTypeScript {
  const cb = new CodeBuilder("  ");
  const scope = new Scope(TS_RESERVED);

  const appId = ctx.app?.id;
  const pkg = ctx.package?.name ?? "unknown";

  const rootBinding = ctx.resolve(ctx.expr);
  const rootType = rootBinding?.type ?? { kind: "struct" as const, fields: {} };

  // Pre-reserve internal generic names that are emitted unconditionally so any
  // IR-derived names colliding with them get suffix-bumped. `Params` is
  // intentionally NOT pre-reserved here - `collectNamedTypes` claims it for
  // the root struct just below.
  const internal = {
    params: "Params",
    outputs: scope.add("Outputs"),
    metadata: scope.add("METADATA"),
    cargs: scope.add("cargs"),
    outputsFn: scope.add("outputs"),
    wrapper: scope.add("run"),
  };

  const { namedTypes, typeDecls } = collectNamedTypes(
    rootType,
    internal.params,
    scope,
    pascalCase,
  );

  // After collectNamedTypes runs, the actual root name may differ from the
  // requested hint if a same-named IR-derived type collided. Use whatever
  // collectNamedTypes assigned.
  const rootName =
    (rootType.kind === "struct" ? namedTypes.get(structKey(rootType)) : undefined) ??
    (rootType.kind === "union" ? namedTypes.get(unionKey(rootType)) : undefined) ??
    internal.params;
  internal.params = rootName;

  // Public-facing tool-prefixed aliases. When no appId is present, the public
  // and internal names coincide and we re-export the internal name as-is.
  const publicNames = {
    params: appId ? pascalCase(appId) : internal.params,
    outputs: appId ? pascalCase(appId) + "Outputs" : internal.outputs,
    metadata: appId ? screamingSnakeCase(appId) + "_METADATA" : internal.metadata,
    cargs: appId ? camelCase(appId) + "_cargs" : internal.cargs,
    outputsFn: appId ? camelCase(appId) + "_outputs" : internal.outputsFn,
    wrapper: appId ? camelCase(appId) : internal.wrapper,
  };

  // Auto-generated header
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  const emitOutputs = hasAnyOutputs(ctx);

  emitImports(cb, emitOutputs);
  cb.blank();

  emitMetadata(ctx, internal.metadata, cb);
  cb.blank();

  emitTypeDeclarations(typeDecls, namedTypes, ctx, internal.params, appId, pkg, cb);

  if (emitOutputs) {
    emitOutputsInterface(ctx, cb);
    cb.blank();
  }

  const paramsType =
    rootType.kind === "struct" || rootType.kind === "union"
      ? internal.params
      : mapType(rootType, resolveTypeName(namedTypes));

  if (emitOutputs && needsStripExtensionsHelper(ctx)) {
    emitStripExtensionsHelper(cb);
    cb.blank();
  }

  emitBuildCargs(ctx, rootType, paramsType, internal.cargs, cb);
  cb.blank();

  if (emitOutputs) {
    emitBuildOutputs(ctx, paramsType, internal.outputsFn, cb);
    cb.blank();
  }

  emitWrapperFunction(
    ctx,
    paramsType,
    internal.wrapper,
    internal.metadata,
    internal.cargs,
    emitOutputs ? internal.outputsFn : undefined,
    cb,
  );
  cb.blank();

  return {
    core: cb.toString(),
    index: generateIndex(internal, publicNames, emitOutputs),
  };
}

/**
 * Build the `index.ts` content - rename re-exports of `./core.js` under
 * tool-prefixed names. When an alias matches its internal name (no appId
 * case) we emit a plain re-export rather than a no-op rename.
 */
function generateIndex(
  internal: PublicSwap,
  publicNames: PublicSwap,
  emitOutputs: boolean,
): string {
  const cb = new CodeBuilder("  ");
  cb.comment("This file was auto generated by Styx.");
  cb.comment("Do not edit this file directly.");
  cb.blank();

  const typeSpecs: string[] = [renameSpec(publicNames.params, internal.params)];
  if (emitOutputs) typeSpecs.push(renameSpec(publicNames.outputs, internal.outputs));

  const valueSpecs: string[] = [
    renameSpec(publicNames.metadata, internal.metadata),
    renameSpec(publicNames.cargs, internal.cargs),
  ];
  if (emitOutputs) valueSpecs.push(renameSpec(publicNames.outputsFn, internal.outputsFn));
  valueSpecs.push(renameSpec(publicNames.wrapper, internal.wrapper));

  cb.line(`export type { ${typeSpecs.join(", ")} } from "./core.js";`);
  cb.line(`export { ${valueSpecs.join(", ")} } from "./core.js";`);

  return cb.toString();
}

function renameSpec(publicName: string, internalName: string): string {
  return publicName === internalName ? internalName : `${internalName} as ${publicName}`;
}

interface PublicSwap {
  params: string;
  outputs: string;
  metadata: string;
  cargs: string;
  outputsFn: string;
  wrapper: string;
}

export class TypeScriptBackend implements Backend {
  readonly name = "typescript";
  readonly target = "typescript";

  emit(ctx: CodegenContext): EmitResult {
    const { core, index } = generateTypeScript(ctx);
    const pkg = ctx.app?.id ?? "output";
    return {
      files: new Map([
        [`${pkg}/index.ts`, index],
        [`${pkg}/core.ts`, core],
      ]),
      errors: [],
      warnings: [],
    };
  }
}
