import type { BoundType } from "../bindings/index.js";
import { Scope } from "./scope.js";
import { structKey, unionKey } from "./type-keys.js";

/** A named compound type (struct or union) discovered during type collection. */
export interface NamedType {
  name: string;
  type: BoundType;
}

/**
 * Recursively collect all struct/union types and assign unique names.
 *
 * Walks the BoundType tree depth-first, using structural keys (`structKey`,
 * `unionKey`) to deduplicate types that appear multiple times in the tree.
 * Each unique struct/union gets a name generated by applying `nameTransform`
 * to a hint string (derived from the root name or field/variant names).
 *
 * @param rootType - The root BoundType to walk.
 * @param rootName - The hint for the root type's name.
 * @param scope - Symbol scope for collision avoidance.
 * @param nameTransform - Converts a hint string to a type name (e.g. pascalCase, snake_case).
 * @returns `namedTypes` maps structural keys to assigned names, `typeDecls` lists declarations in order.
 */
export function collectNamedTypes(
  rootType: BoundType,
  rootName: string,
  scope: Scope,
  nameTransform: (hint: string) => string,
): { namedTypes: Map<string, string>; typeDecls: NamedType[] } {
  const namedTypes = new Map<string, string>();
  const typeDecls: NamedType[] = [];

  function visit(type: BoundType, hint: string): void {
    switch (type.kind) {
      case "struct": {
        const key = structKey(type);
        if (!namedTypes.has(key)) {
          const name = scope.add(nameTransform(hint));
          namedTypes.set(key, name);
          typeDecls.push({ name, type });
          for (const [fieldName, fieldType] of Object.entries(type.fields)) {
            visit(fieldType, fieldName);
          }
        }
        break;
      }
      case "union": {
        const key = unionKey(type);
        if (!namedTypes.has(key)) {
          const name = scope.add(nameTransform(hint));
          namedTypes.set(key, name);
          typeDecls.push({ name, type });
          for (const v of type.variants) {
            visit(v.type, v.name ?? hint);
          }
        }
        break;
      }
      case "optional":
        visit(type.inner, hint);
        break;
      case "list":
        visit(type.item, hint);
        break;
      default:
        break;
    }
  }

  visit(rootType, rootName);
  return { namedTypes, typeDecls };
}

/**
 * Create a type name resolver from a namedTypes map.
 * Returns a function that maps a BoundType to its assigned name (if any).
 */
export function resolveTypeName(
  namedTypes: Map<string, string>,
): (type: BoundType) => string | undefined {
  return (type) => {
    if (type.kind === "struct") return namedTypes.get(structKey(type));
    if (type.kind === "union") return namedTypes.get(unionKey(type));
    return undefined;
  };
}
