import type { BoundType } from "../bindings/index.js";
import { Scope } from "./scope.js";
import { structKey, unionKey } from "./type-keys.js";

/** A named compound type (struct or union) discovered during type collection. */
export interface NamedType {
  name: string;
  type: BoundType;
}

/**
 * Recursively collect all struct/union types and assign unique names.
 *
 * Walks the BoundType tree depth-first, using structural keys (`structKey`,
 * `unionKey`) to deduplicate types that appear multiple times in the tree.
 * Each unique struct/union gets a name generated by applying `nameTransform`
 * to a hint string (derived from the root name or field/variant names).
 *
 * @param rootType - The root BoundType to walk.
 * @param rootName - The hint for the root type's name (already tool-qualified).
 * @param scope - Symbol scope for collision avoidance.
 * @param nameTransform - Converts a hint string to a type name (e.g. pascalCase, snake_case).
 * @param nestedPrefix - Prepended to every NON-root type name so a suite's flat
 *   barrel (`export * from`/`from .x import *`) can't collide two tools' types
 *   that share a local field/variant name (e.g. `Outputtype`). Pass the tool's
 *   type prefix (its root name); defaults to "" for single-tool emission.
 * @returns `namedTypes` maps structural keys to assigned names, `typeDecls` lists declarations in order.
 */
export function collectNamedTypes(
  rootType: BoundType,
  rootName: string,
  scope: Scope,
  nameTransform: (hint: string) => string,
  nestedPrefix = "",
): { namedTypes: Map<string, string>; typeDecls: NamedType[] } {
  const namedTypes = new Map<string, string>();
  const typeDecls: NamedType[] = [];

  function nameFor(hint: string, isRoot: boolean): string {
    return scope.add(isRoot ? nameTransform(hint) : nestedPrefix + nameTransform(hint));
  }

  function visit(type: BoundType, hint: string, isRoot: boolean): void {
    switch (type.kind) {
      case "struct": {
        const key = structKey(type);
        if (!namedTypes.has(key)) {
          const name = nameFor(hint, isRoot);
          namedTypes.set(key, name);
          typeDecls.push({ name, type });
          for (const [fieldName, fieldType] of Object.entries(type.fields)) {
            visit(fieldType, fieldName, false);
          }
        }
        break;
      }
      case "union": {
        const key = unionKey(type);
        if (!namedTypes.has(key)) {
          const name = nameFor(hint, isRoot);
          namedTypes.set(key, name);
          typeDecls.push({ name, type });
          for (const v of type.variants) {
            visit(v.type, v.name ?? hint, false);
          }
        }
        break;
      }
      // Wrappers are transparent: an optional/list at the root still names its
      // inner type as the root (no prefix), matching the pre-prefix behavior.
      case "optional":
        visit(type.inner, hint, isRoot);
        break;
      case "list":
        visit(type.item, hint, isRoot);
        break;
      default:
        break;
    }
  }

  visit(rootType, rootName, true);
  return { namedTypes, typeDecls };
}

/**
 * Create a type name resolver from a namedTypes map.
 * Returns a function that maps a BoundType to its assigned name (if any).
 */
export function resolveTypeName(
  namedTypes: Map<string, string>,
): (type: BoundType) => string | undefined {
  return (type) => {
    if (type.kind === "struct") return namedTypes.get(structKey(type));
    if (type.kind === "union") return namedTypes.get(unionKey(type));
    return undefined;
  };
}
